### ISSUE TITLE
Question about semantic 'format' validation

### ISSUE THREAD

**Issue by torarvid** [tdegrunt/jsonschema#118]
This may or may not be right, but as I understood the json schema standard, it should be ok for me to define my own custom 'format' specifiers. So I might say

    ...
    {
        "type": "string",
        "format": "image-as-base-64"
    }

and it seems to me that if that format doesn't exist in your validator, the default should be successful validation. But currently it gives an error, right?

**Comment by Acubed** [comment]
This seems to have been fixed in development, per discussion at #109

Perhaps this needs to get into the official JSON Schema test suite though.

**Comment by lupugabriel1** [comment]
This problem is still active, in my case I have :
```javascript
{
    "type": "string",
    "format": "uuid"
}
```
Since ``uuid`` is not defined as one of the formatting options ( ``FORMAT_REGEXPS`` in [helpers.js](https://github.com/tdegrunt/jsonschema/blob/master/lib/helpers.js) ), [isFormat](https://github.com/tdegrunt/jsonschema/blob/master/lib/helpers.js#L152) function is returning false, causing the validation to fail. Instead, I think the module should support additional formatting options.

Example:
```javascript
var Validator = require('jsonschema').Validator;
// When creating the instance
var v = new Validator({
    formats: {
        'uuid': /[\w]{8}(-[\w]{4}){3}-[\w]{12}/
    }
});

// Calling a function on the instance
v.addFormat({'image-as-base-64': /base64/);
```
If interested in this approach, I can submit a PR. 

Thanks !

**Comment by acusti** [comment]
Definitely the “correct” solution to this would be to allow people to register their own custom formats. The tv4 package handles this via an [`addFormat` API method](https://github.com/geraintluff/tv4/#addformatformat-validationfunction). That method takes a format name and a formatting validator function, which returns `null` if no error, else a string describing the error that was created.
